language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install flake8 pep8-naming flake8-quotes flake8-import-order pylint
before_script:
  - flake8 --max-line-length=99 --import-order-style=google
  - pylint -E dice.py distribution.py eote_dice.py test.py
script:
  python -Werror -m coverage run test.py
after_success:
  codecov